# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7.x' 
    addToPath: true 
    architecture: 'x64' # Options x86, x64 (this argument applies only on Windows agents)
  displayName: 'Install Python 2.x'

- script: |
    npm install
  displayName: 'Install NPM modules'

- script: |
    npm install -g node-gyp
    node-gyp rebuild
  displayName: 'Build C++ module'

- script: |
    npm test
  displayName: 'Run NPM tests'
